abbr g 'git'

abbr ga 'git add'
abbr ga. 'git add .'

abbr gb 'git branch'
abbr gbd 'git branch -D'
abbr gbl 'git blame -b -w'
abbr gbnm 'git branch --no-merged'
abbr gbr 'git branch --remote'
abbr gbs 'git bisect'
abbr gbsb 'git bisect bad'
abbr gbsg 'git bisect good'
abbr gbsr 'git bisect reset'
abbr gbss 'git bisect start'

abbr gc 'git commit -v'
abbr gc! 'git commit -v --amend'
abbr gcn! 'git commit -v --no-edit --amend'
abbr gca 'git commit -v -a'
abbr gca! 'git commit -v -a --amend'
abbr gcan! 'git commit -v -a --no-edit --amend'
abbr gcans! 'git commit -v -a -s --no-edit --amend'
abbr gcam 'git commit -a -m'
abbr gcsm 'git commit -s -m'
abbr gco 'git checkout'
abbr gco- 'git checkout -'
abbr gcb 'git checkout -b'
abbr gcf 'git config --list'
abbr gcm 'git checkout master'
abbr gcd 'git checkout develop'
abbr gcdl 'git checkout develop; and git pull'
abbr gcmsg 'git commit -m'
abbr gcp 'git cherry-pick'
abbr gcpa 'git cherry-pick --abort'
abbr gcpc 'git cherry-pick --continue'
abbr gcs 'git commit -S'

abbr gd 'git diff'
abbr gdca 'git diff --cached'
abbr gdct 'git describe --tags `git rev-list --tags --max-count 1`'
abbr gdt 'git diff-tree --no-commit-id --name-only -r'
abbr gdw 'git diff --word-diff'

abbr gf 'git fetch'
abbr gfp 'git fetch -p'
abbr gfo 'git fetch origin'

abbr gl 'git pull'
abbr glg 'git log --stat'
abbr glgp 'git log --stat -p'
abbr glgg 'git log --graph'
abbr glgga 'git log --graph --decorate --all'
abbr glgm 'git log --graph --max-count 10'
abbr glo 'git log --oneline --decorate'
abbr glol "git log --graph --pretty '%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
abbr glola "git log --graph --pretty '%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
abbr glog 'git log --oneline --decorate --graph'
abbr gloga 'git log --oneline --decorate --graph --all'

abbr gm 'git merge'
abbr gmom 'git merge origin/master'
abbr gmt 'git mergetool --no-prompt'
abbr gmtvim 'git mergetool --no-prompt --tool vimdiff'
abbr gmum 'git merge upstream/master'

abbr gp 'git push'
abbr gpd 'git push --dry-run'
abbr gpoat 'git push origin --all; and git push origin --tags'
abbr gpuo 'git push -u origin'
abbr gpv 'git push -v'

abbr gr 'git remote'
abbr gra 'git remote add'
abbr grb 'git rebase'
abbr grba 'git rebase --abort'
abbr grbc 'git rebase --continue'
abbr grbi 'git rebase -i'
abbr grbm 'git rebase master'
abbr grbs 'git rebase --skip'
abbr grh 'git reset HEAD'
abbr grhh 'git reset HEAD --hard'
abbr grmv 'git remote rename'
abbr grrm 'git remote remove'
abbr grset 'git remote set-url'
abbr gru 'git reset --'
abbr grup 'git remote update'
abbr grv 'git remote -v'

abbr gsb 'git status -sb'
abbr gsd 'git svn dcommit'
abbr gsi 'git submodule init'
abbr gss 'git status -s'
abbr gst 'git status'
abbr gsta 'git stash save'
abbr gstaa 'git stash apply'
abbr gstc 'git stash clear'
abbr gstd 'git stash drop'
abbr gstl 'git stash list'
abbr gstp 'git stash pop'
abbr gsts 'git stash show --text'

abbr gts 'git tag -s'
abbr gup 'git pull --rebase'
abbr gupv 'git pull --rebase -v'

abbr gwch 'git whatchanged -p --abbrev-commit --pretty medium'
