abbr ya 'yarn --ignore-engines add '
abbr yj 'yarn jest'
abbr yl 'yarn lint'
abbr cpj 'cd packages/jsfiller3'
abbr cps 'cd packages/snfiller'
abbr cj 'cd ~/jsfiller'
abbr ys 'yarn start'
abbr yjf 'yarn jsfiller'
abbr ysf 'yarn snfiller'
abbr y 'yarn --ignore-engines'
